export const NO_MCP_SERVERS_SENTINEL = "NO_MCP_SERVERS";
export const MCP_TOOLS_PREVIEW_FORBIDDEN_MESSAGE = "MCP tools preview forbidden";
export const ALL_PROXY_MCP_SERVERS_SENTINEL = "ALL_PROXY_MCP_SERVERS";
